name: Create Hospitality
favicon: null
layout_spectrum: 0.25337
typography_spectrum: 0.56193
title: 'F&B holding company in Dubai'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#878787'
    - '#3c3c3c'
    - '#696969'
    - '#cacaca'
  brandStrength: 0.08842053893022239
  lightness: 0.22604131721891463
  saturation: 0.31714735040441155
  rhythmicContrast: 0.07244598935358226
purpose: []
